on:
  push:
    paths: 
      - 'hw.tex'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile TeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: hw.tex

      - uses: actions/upload-artifact@v2
        with:
          name: Homework
          path: ./hw.pdf

      - name: Push to remote
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add hw.pdf
          git commit -m "Upload pdf"
          git push
